---
- name: dns
  hosts: all

  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - nmcli:
        conn_name: Wired connection 1
        type: ethernet
        dns4:
          - 9.6.24.95
          - 9.6.24.96
        state: present
      become: yes

    - nmcli:
        conn_name: Wired connection 2
        type: ethernet
        dns4:
          - 9.6.24.95 
          - 9.6.24.96
        state: present
      become: yes
      ignore_errors: True

#    - name: Reboot a slow machine that might have lots of updates to apply
#      ansible.builtin.reboot:
#        reboot_timeout: 3600
#      become: yes

    - name: Get Kernel version
      shell: uname -r
      register: kernel_shell_output

    - debug: msg="{{ kernel_shell_output.stdout}}"

#    - name: Hold kernel
#      dpkg_selections:
#        name: "{{ kernel_shell_output.stdout}}"
#        selection: hold
#      become: yes

    - name: Hold Kernel version
      shell: sudo apt-mark hold {{ kernel_shell_output.stdout}}
      become: yes

    - name: Get Hold status
      shell: dpkg -l|grep linux|grep "^hi"
      register: hold

    - debug: msg="{{ hold.stdout}}"
      
    - name: dnssec
      lineinfile:
        path: /etc/systemd/resolved.conf
        line: 'DNSSEC=no'
        insertafter: EOF
        backup: yes
      become: yes

    - name: restart resolver
      service:
        name: systemd-resolved.service
        state: restarted
      become: yes

    - name: Reboot a slow machine that might have lots of updates to apply
      ansible.builtin.reboot:
        reboot_timeout: 3600
      become: yes
