---
- name: Prepare sound settings to new shop newtwork
  hosts:  all
  vars:
    vol:  50
  gather_facts: false
  become: yes
  tasks:

    
    - name: Check current root crontab
      shell:  crontab -u root -l
      register: root_cron
      ignore_errors:  yes
    - debug:  var=root_cron.stdout_lines

    # - name: Check current root crontab
    #   shell:  crontab -u root -r

    - name: Set cron reboot every 15 days
      cron:
        minute: 0
        hour: 10
        day:  "*"
        month:  "*"
        weekday:  "*"
        job:  sudo ffplay -nodisp -autoexit /opt/unlift/unlift_proxy/warning.mp3
        state:  present

    - name: Fill the crontab
      cron:
        special_time: reboot
        job:  '{{ item }}'
        state:  present
      with_items:
        - '0 10 * * * curl --header "Content-Type: application/json" --request POST --data '' http://localhost:5477/test'
        - '@reboot sleep 30; sudo amixer set Master playback {{ vol }}\%;sudo amixer set Master unmute; sudo alsactl store'
        - '@reboot sleep 30; sudo amixer set Headphone playback {{ vol }}\%;sudo amixer set Headphone unmute;sudo amixer -D default sset "Auto-Mute Mode" Disabled; sudo alsactl store'
    
    - name: Check current root crontab
      shell:  crontab -u root -l
      register: root_cron
      ignore_errors:  yes
    - debug:  var=root_cron.stdout_lines

    - name: reboot machine
      reboot:

    - name: sound check
      shell:  sudo ffplay -nodisp -autoexit /opt/unlift/unlift_proxy/warning.mp3