---
- name: Transfer and execute a script.
  hosts: all
  remote_user: detect
  tasks:
    - name: Restart service bit-alert
      ansible.builtin.service:
        name: zabbix-agent
        state: restarted
      become: yes
