---
- name: Transfer and execute a script.
  hosts: all
  remote_user: detect
  tasks:
    - name: Transfer the ini
      ansible.posix.synchronize:
        src: /home/detect/ff451/findface-extraction-api.ini
        dest: /home/{{ansible_user}}/
        partial: yes
    - name: copy file on machine
      command: cp /home/{{ansible_user}}/findface-extraction-api.ini /etc/
      become: yes
    - name: Restart service bit-alert
      ansible.builtin.service:
        name: findface-extraction-api
        state: restarted
      become: yes
