---
- name: Set alsa sound settings
  hosts:  all
  become: yes
  vars:
    vol:  100
    record_to_play: /opt/unlift/unlift_proxy/warning.mp3
  tasks:


    # - name: Add proxy
    #   shell:  echo 'Acquire::http::Proxy "http://face452k.bit-tech.co:8105";'|sudo tee /etc/apt/apt.conf.d/00aptproxy

    # - name: sudo apt install alsa-tools
    #   apt:
    #     name: alsa-tools
    #     state:  present
    #   ignore_errors: yes

    - name: Check current root crontab
      shell:  crontab -u root -l
      register: root_cron
      ignore_errors:  yes
    - debug:  var=root_cron.stdout_lines

    # - name: remove old crontab
    #   shell: sudo crontab -u root -r

    # - name: Check current root crontab
    #   shell:  crontab -u root -r

    - name: Set cron reboot every 15 days
      cron:
        minute: 0
        hour: 10
        day:  15
        month:  "*"
        weekday:  "*"
        job:  sudo ffplay -nodisp -autoexit /opt/unlift/unlift_proxy/warning.mp3
        state:  present
    
    - name: Fill the crontab
      cron:
        special_time: reboot
        job:  '{{ item }}'
        state:  present
      with_items:
        - 'sleep 30; sudo amixer set Master playback {{ vol }}\%;sudo amixer set Master unmute; sudo alsactl store'
        - 'sleep 30; sudo amixer set Headphone playback {{ vol }}\%;sudo amixer set Headphone unmute;sudo amixer -D default sset "Auto-Mute Mode" Disabled; sudo alsactl store'
        - 'sleep 30; sudo amixer -D default sset \"Auto-Mute Mode\" Disabled; sudo alsactl store'
        - 'sleep 30; sudo amixer set Line playback {{ vol }}\%;sudo amixer set Line unmute; sudo alsactl store'
        - 'sleep 30; sudo amixer set Surround playback {{ vol }}\%;sudo amixer set Surround unmute; sudo alsactl store'
        - 'sleep 30; sudo amixer set Center playback {{ vol }}\%;sudo amixer set Center unmute; sudo alsactl store'
        - 'sleep 30; sudo amixer set LFE playback {{ vol }}\%;sudo amixer set LFE unmute; sudo alsactl store'
        - 'sleep 30; sudo amixer set Line Boost playback {{ vol }}\%;sudo amixer set Line Boost unmute; sudo alsactl store'
        - 'sleep 30;sudo amixer set S/PDIF unmute; sudo alsactl store'


    - name: Check current root crontab
      shell:  crontab -u root -l
      register: root_cron
      ignore_errors:  yes
    - debug:  var=root_cron.stdout_lines

    - name: reboot machine
      reboot:

    - name: sound check
      shell:  sudo ffplay -nodisp -autoexit {{ record_to_play }}
