---
- name: Transfer and execute a script.
  hosts: inst
  gather_facts: false
  tasks:

    - name: install basic packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ntp
      become: yes

    - name: Input shop type
      prompt: 'Input timesrv'
      register: choice
    - debug:  msg="Your choice is {{ choice }}"

    - name: Set fact - timesrv
      set_fact:
        timesrv:  '{{ choice.stdout }}'

    - name: echo "server ntp1" | sudo tee /etc/ntp.conf
      shell: echo "server {{timesrv}}" | sudo tee /etc/ntp.conf
      become: yes

    - name: echo "server 1.pool.ntp.org" | sudo tee -a /etc/ntp.conf
      shell: echo "server 1.pool.ntp.org" | sudo tee -a /etc/ntp.conf
      become: yes

    - name: sudo service timesyncd stop
      service:
        name: systemd-timesyncd
        state: stopped
        enabled: no
      become: yes

    - shell: sudo service ntp stop;sudo ntpd -gq;sudo service ntp start
      become: yes

    - name: sudo service ntp restart
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
	      - ntp
	      - unlift
        - unlift-updater
      become: yes


