---
- name: Set check unlift_diag
  hosts:  all
  tasks:

  - name: Check status of file - /opt/unlift/unlift_proxy/unlift_diag.py
    stat:
      path: /opt/unlift/unlift_proxy/unlift_diag.py
    register: st
    become: yes

  - name: fail if file exist
    fail:
      msg:  "File is already there!"
    when: st.stat.islnk is defined

  - name: Create task on cron
    cron:
      name: check
      special_time: hourly
      user: root
      job: 'python3 /opt/unlift/unlift_proxy/unlift_diag.py -c /etc/unlift.ini|logger'
      state: present
    become: yes


  - name: Check cron
    shell:  sudo crontab -l
    register: cron
    become: yes
  - debug:  var=cron.stdout_lines


  - name: Sed /etc/unlift "currentvarsion = "
    replace:
      path: /etc/unlift-updater.ini
      regexp: 'currentversion = *'
      replace:  'currentversion = 1'
    become: yes

  - name: restart unlift-updater
    systemd:
      name: unlift-updater
      state:  restarted
    become: yes

  - name: cat /etc/unlift-updater.ini
    shell:  cat /etc/unlift-updater.ini
    register: updater
    become: yes
  - debug:  var=updater.stdout_lines
