---
- hosts: all
#  connection: local
#  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

  - name: sync files
    synchronize:
      src: files/findface-repo.deb
      dest: /home/{{ansible_user}}/
      partial: yes

  - name: Get Kernel version
    shell: uname -r
    register: kernel_shell_output

  - debug: msg="{{ kernel_shell_output.stdout}}"

  - name: Hold Kernel version
    shell: sudo apt-mark hold {{ kernel_shell_output.stdout}}
    become: yes

  - name: Get Hold status
    shell: dpkg -l|grep linux|grep "^hi"
    register: hold

  - debug: msg="{{ hold.stdout}}"

  - name: install deb
    apt:
      deb: /home/{{ansible_user}}/findface-repo.deb
    become: yes
    ignore_errors: True

  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    become: yes

  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes
    become: yes
